import patchSchema from '../../schemas/patch.schema.json';
import { PATCH_DOCUMENT_VERSION, graphDocumentToPatch } from '@open-din/react';

describe('patch schema contract', () => {
    it('keeps the published schema aligned with the current patch version and public interface shape', () => {
        expect(patchSchema.$schema).toBe('https://json-schema.org/draft/2020-12/schema');
        expect(patchSchema.properties.version.const).toBe(PATCH_DOCUMENT_VERSION);
        expect(patchSchema.required).toEqual(
            expect.arrayContaining(['version', 'name', 'nodes', 'connections', 'interface'])
        );
        expect(patchSchema.$defs.patchInterface.required).toEqual(
            expect.arrayContaining(['inputs', 'events', 'midiInputs', 'midiOutputs'])
        );
        expect(patchSchema.$defs.nodeType.enum).toEqual(
            expect.arrayContaining(['input', 'eventTrigger', 'midiNote', 'midiCC', 'midiNoteOutput', 'midiCCOutput', 'midiSync', 'sampler', 'convolver', 'output'])
        );
    });

    it('matches the top-level structure generated by graphDocumentToPatch', () => {
        const patch = graphDocumentToPatch({
            name: 'Schema Patch',
            nodes: [
                {
                    id: 'output-1',
                    position: { x: 0, y: 0 },
                    data: { type: 'output', label: 'Output', playing: false, masterGain: 0.5 },
                },
            ],
            edges: [],
        });

        expect(patch.version).toBe(patchSchema.properties.version.const);
        expect(Object.keys(patch).sort()).toEqual(['connections', 'interface', 'name', 'nodes', 'version']);
        expect(patch.interface).toEqual({
            inputs: [],
            events: [],
            midiInputs: [],
            midiOutputs: [],
        });
    });
});
