import patchSchema from '../../schemas/patch.schema.json';
import { PATCH_DOCUMENT_VERSION, graphDocumentToPatch } from '@open-din/react';

describe('patch schema contract', () => {
    it('keeps the published schema aligned with the current patch version and public interface shape', () => {
        expect(patchSchema.$schema).toBe('https://json-schema.org/draft/2020-12/schema');
        expect(patchSchema.properties.version.const).toBe(PATCH_DOCUMENT_VERSION);
        expect(patchSchema.required).toEqual(
            expect.arrayContaining(['version', 'name', 'nodes', 'connections', 'interface'])
        );
        expect(patchSchema.$defs.patchInterface.required).toEqual(
            expect.arrayContaining(['inputs', 'events', 'midiInputs', 'midiOutputs'])
        );
        expect(patchSchema.$defs.nodeType.enum).toEqual(
            expect.arrayContaining([
                'input',
                'eventTrigger',
                'midiNote',
                'midiCC',
                'midiNoteOutput',
                'midiCCOutput',
                'midiSync',
                'midiPlayer',
                'patch',
                'sampler',
                'convolver',
                'output',
            ])
        );
        expect(patchSchema.$defs.slotType.enum).toEqual(['audio', 'midi']);
        expect(patchSchema.$defs.patchSlot.required).toEqual(expect.arrayContaining(['id', 'label', 'type']));
        expect(patchSchema.$defs.patchAudioMetadata.required).toEqual(expect.arrayContaining(['input', 'output']));
        expect(Object.keys(patchSchema.$defs.patchNodeData.properties)).toEqual(
            expect.arrayContaining(['patchAsset', 'patchInline', 'patchName', 'inputs', 'outputs', 'audio'])
        );
    });

    it('matches the top-level structure generated by graphDocumentToPatch', () => {
        const patch = graphDocumentToPatch({
            name: 'Schema Patch',
            nodes: [
                {
                    id: 'output-1',
                    position: { x: 0, y: 0 },
                    data: { type: 'output', label: 'Output', playing: false, masterGain: 0.5 },
                },
            ],
            edges: [],
        });

        expect(patch.version).toBe(patchSchema.properties.version.const);
        expect(Object.keys(patch).sort()).toEqual(['connections', 'interface', 'name', 'nodes', 'version']);
        expect(patch.interface).toEqual({
            inputs: [],
            events: [],
            midiInputs: [],
            midiOutputs: [],
        });
    });

    it('canonicalizes patch node boundary metadata with implicit audio slots', () => {
        const inlinePatch = graphDocumentToPatch({
            name: 'Inline Child Patch',
            nodes: [],
            edges: [],
        });

        const patch = graphDocumentToPatch({
            name: 'Patch Node Contract',
            nodes: [
                {
                    id: 'patch-1',
                    position: { x: 0, y: 0 },
                    data: {
                        type: 'patch',
                        label: 'Nested Patch',
                        patchAsset: '/patches/child.din',
                        patchInline: inlinePatch,
                        patchName: 'Child Patch',
                        inputs: [{ id: 'keys', label: 'Keys', type: 'midi' }],
                        outputs: [{ id: 'mix', label: 'Mix', type: 'audio' }],
                        audio: {
                            input: { id: 'in', label: 'Audio In', type: 'audio' },
                            output: { id: 'out', label: 'Audio Out', type: 'audio' },
                        },
                    },
                },
            ],
            edges: [],
        });

        expect(patch.nodes[0]).toMatchObject({
            type: 'patch',
            data: {
                type: 'patch',
                patchAsset: '/patches/child.din',
                patchInline: inlinePatch,
                patchName: 'Child Patch',
                inputs: [{ id: 'keys', label: 'Keys', type: 'midi' }],
                outputs: [{ id: 'mix', label: 'Mix', type: 'audio' }],
                audio: {
                    input: { id: 'in', label: 'Audio In', type: 'audio' },
                    output: { id: 'out', label: 'Audio Out', type: 'audio' },
                },
            },
        });
    });
});
